### ISSUE TITLE
undefined method "organization_member?" for Hash

### ISSUE THREAD

**Issue by st0012** [fphilipe/warden-github-rails#18]
Hi, I recently ran into an issue in [this line](https://github.com/fphilipe/warden-github-rails/blob/master/lib%2Fwarden%2Fgithub%2Frails%2Froutes.rb#L63) of code. It calls `organization_member?` method to the user argument, which is [fetched from warden](https://github.com/fphilipe/warden-github-rails/blob/master/lib%2Fwarden%2Fgithub%2Frails%2Froutes.rb#L47) using `warden.user`. And since `warden.user` returns a `Hash`, the error occurs.
So I want to ask that if this is a bug, or I misunderstand something? Thank you :smile:

**Comment by fphilipe** [comment]
Shouldn't be the case. This is handled by [warden-github](/atmos/warden-github). Could you post some code and version numbers?

**Comment by st0012** [comment]
I just solved this, thanks!
