### ISSUE TITLE
Testing and Rails 4

### ISSUE THREAD

**Issue by atmos** [fphilipe/warden-github-rails#4]
I've been trying to use the test helpers in rails 4 with rspec-rails and no matter how I create the user my first request is always a 302 to github.

**Comment by Goblue1616** [comment]
I'm having the same issue:

1. include Warden::GitHub::Rails::TestHelpers is giving the following error:

2: The following code:
subject { get '/clients' }
it { is_expected.to be_github_oauth_redirect }

yields:

**Comment by fphilipe** [comment]
@Goblue1616 2. is happening because of 1. Are you requiring the test helpers? `require 'warden/github/rails/test_helpers'`

**Comment by Goblue1616** [comment]
Gotcha!  Thanks for the help.
